on: 
  workflow_dispatch: 
  pull_request: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 05 5 * * 1

name: Semgrep
jobs:
  buildGradleLockFile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build Dependency Lock File
        run: ./gradlew dependencies --write-locks
      - name: Display 
        run: ls -lah
      - name: Display 
        run: tree
      - name: Upload Gradle Lock File
        uses: actions/upload-artifact@v4
        with:
          name: gradlelockfiles
          path: gradle.lockfile
  semgrep:
    needs: buildGradleLockFile
    name: Scan
    runs-on: ubuntu-24.04
    env:
      SEMGREP_APP_TOKEN: $ secrets.SEMGREP_APP_TOKEN 
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: gradlelockfiles
      - run: semgrep ci
